# 🐳 Docker Compose para API MLOps
# =================================
version: '3.8'

services:
  # Servicio principal de la API
  mlops-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mlops-recomendaciones-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENV=production
    volumes:
      # Opcional: Para persistir logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/salud"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mlops-network

  # Opcional: Nginx como proxy reverso (para producción)
  nginx:
    image: nginx:alpine
    container_name: mlops-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mlops-api
    restart: unless-stopped
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge

volumes:
  logs:
    driver: local